# Generated by Django 3.2.8 on 2021-10-17 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('surname', models.CharField(max_length=300, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=300, verbose_name='Отчество')),
                ('image', models.ImageField(upload_to='artists/', verbose_name='Изображение')),
                ('location', models.CharField(max_length=450, verbose_name='Адрес')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('description', models.TextField(verbose_name='Описание')),
                ('education', models.TextField(verbose_name='Образование')),
                ('facebook', models.CharField(blank=True, max_length=300, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=300, verbose_name='Instagram')),
                ('site', models.CharField(blank=True, max_length=200, verbose_name='Сайт')),
                ('nft_platform', models.CharField(blank=True, max_length=300, verbose_name='Платформа NFT')),
                ('phone', models.CharField(max_length=22, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Artworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название работы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='artworks/normal/', verbose_name='Изображение')),
                ('quality_image', models.ImageField(upload_to='artworks/hd/', verbose_name='Изображение-HD')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год создания')),
                ('location', models.CharField(max_length=350, verbose_name='Месонахождение предмета')),
                ('owner', models.CharField(blank=True, max_length=300, verbose_name='Владелец')),
                ('price', models.PositiveIntegerField(default=0, help_text='Укажите сумму в рублях', verbose_name='Цена')),
                ('in_sale', models.BooleanField(default=False, verbose_name='В продаже')),
                ('signature', models.CharField(help_text='Как и где автор оставил свою подпись', max_length=300, verbose_name='Идентификация автора')),
                ('certificate_of_auth', models.CharField(blank=True, help_text='Проверка галереей', max_length=300, verbose_name='Подтверждение подлинности')),
                ('frame', models.BooleanField(default=False, verbose_name='Наличие рамки')),
                ('size', models.CharField(max_length=350, verbose_name='Размер предмета')),
                ('tags', models.CharField(default='', max_length=350, verbose_name='Теги')),
                ('url', models.SlugField(max_length=180, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_artist', to='artworks.artists', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=180, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_ru', models.CharField(max_length=140, verbose_name='Название на русском')),
                ('label_en', models.CharField(max_length=140, verbose_name='Название на английском')),
                ('domain', models.CharField(blank=True, max_length=10, null=True, verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Raitingstar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звезды рейтинга',
            },
        ),
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Техника работы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=180, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Техники',
            },
        ),
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP-адрес')),
                ('artworks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artworks', verbose_name='работа')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.raitingstar', verbose_name='звезда')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('artworks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artworks', verbose_name='Работа')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.comment', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='artworks',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='artworks',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='artworks',
            name='technic_paint',
            field=models.ManyToManyField(related_name='artwork_technic', to='artworks.Technic', verbose_name='Техника'),
        ),
        migrations.AddField(
            model_name='artists',
            name='technic_favorite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.category', verbose_name='Техника работы художника'),
        ),
    ]
